### ISSUE TITLE
Inconsistent average donation values on Sundays

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#15]
Context : commit aa0be20992855001e9f01061ba705daa500d4f1c (HEAD -> master, origin/master, origin/HEAD)

I observe inconsistent average donation values.
With a cron executed at Sun Mar 24 10:00:03:03 2019, i have :   
<img width="109" alt="Capture d’écran 2019-03-24 à 10 08 34" src="https://user-images.githubusercontent.com/37941899/54877297-cf91cb00-4e1c-11e9-92d5-916dcfb4e4cc.png">
The reset seems to be 24 hours too early. 
At that time, the donation value should be almost divided by 7, and not 1.

**Comment by Eagle334** [comment]
With some debug line, it confirms that on Sundays, "days_from_donation_reset" = 1 instead of 7.
```
    days_from_donation_reset = now.isoweekday()

    logger.debug("# days_from_donation_reset: {}".format(days_from_donation_reset))

    if days_from_donation_reset >= 7 or days_from_donation_reset <= 0:
        days_from_donation_reset = 1

    logger.debug("#days_from_donation_reset if: {}".format(days_from_donation_reset))
```
returns:
```
DEBUG:crtools.crtools:# days_from_donation_reset: 7
DEBUG:crtools.crtools:#days_from_donation_reset if: 1

```

I change into :  
```
if days_from_donation_reset > 7 or days_from_donation_reset <= 0:
        days_from_donation_reset = 1
```
and now it's OK.

**Comment by Eagle334** [comment]
I check your https://agrassar.com/ and you have the same issue ;o)

**Comment by AaronTraas** [comment]
@Eagle334 I applied your change to version 1.15.16
