### ISSUE TITLE
Mobile mode doesn't work

### ISSUE THREAD

**Issue by coolnickname** [AaronTraas/Clash-Royale-Clan-Tools#16]
I just installed this but for some reason on mobile devices it shows the desktop version, unlike the example site in readme which does show properly.

Do I need to to enable it manually or something?

**Comment by coolnickname** [comment]
Apache on Ubuntu 18.04 btw

**Comment by AaronTraas** [comment]
Can you please show a screenshot? The app is responsive. Should work on mobile. 

Do you see https://agrassar.com render correctly on mobile?

**Comment by Eagle334** [comment]
![Screenshot_20190416-075814](https://user-images.githubusercontent.com/37941899/56317714-b222f900-615d-11e9-8df5-8b4b0fb363fb.jpg)
It's OK for me ;)

**Comment by AaronTraas** [comment]
@coolnickname -- I'm closing this as you haven't followed up. If you still have an issue that persists, feel free to re-open.
