### ISSUE TITLE
Stats per player based on the 10 last war

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#17]
It would be nice to have statistics per player based on the last 10 wars.
For example: 
 - Win rate (# war day win /10)
 - Collection day wins mean value = Sum 'Collection day wins' / 10
 - Card earned mean value = Sum 'Card earned' / 10
 - War score mean value = Sum 'War score' /10

**Comment by AaronTraas** [comment]
Done:

<img width="654" alt="Screen Shot 2019-09-13 at 11 50 03 AM" src="https://user-images.githubusercontent.com/1229439/64876300-d86d9780-d61c-11e9-9904-93a35f0f138c.png">
