### ISSUE TITLE
How to customize the v2

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#18]
Hello Aaron, 
Next to the v2.x update, now i use "pip3 install -U crtools" that consume directly your code. 
How can i continue to translate it in french for my clan and compile a local version ?
Thanks

**Comment by AaronTraas** [comment]
In that method, you can't. You can still use the old installation method, however. 

I need to work on the internationalization so you don't have to apply any changes.
