### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#2]
Hello Aaron,
I use your code for a french Clash Royal clan (#Q8JL00). Currently I am doing stats in a Google Sheet table, and I would like to automate updates via API requests.
I discovered your code, it allows to have a lot of interesting information based on the CR API. In my copy I have already translated almost everything into French. And I have a lot of desire for improvement but I'm not comfortable in Python/JS or CSS.
Among my ideas, I would like to store the data and not just suffer the 10 wars given by the API. And for donations, to have several weeks. In my Google Sheet, I make statistics on 6 weeks of donations, and 14 days of war (2 seasons). 
I promote the Members after 3 weeks of compliance with my rules (donations + war). I have a top 10 of Co-Leader based on donations + war (not necessarily the 10 strongest in crowns) over 9 weeks. And I keep the history of all the players who came to the clan, in case they come back and they behaved badly.
I'd like to know if you are planning on making that kind of evolution, with a nice and effective code. Or if I have to try it in my side but it's going to be less pretty and efficient. ;)

**Comment by AaronTraas** [comment]
@Eagle334 hey -- thanks for the comment. Sorry I didn't see it earlier.

I added a rudimentary history storage. Not using a database file, but a JSON manifest that gets updated every time it runs. The only thing the history keeps track of right now is member join/quit and promotions/demotions. 

I was planning on adding multilingual support eventually. But history is my first priority right now, as is getting closer to full test coverage. I just added unit tests this past weekend, and integrated with CI and static analysis.

When I do add multilingual support, it will likely be in the form of an external JSON or YAML file that contains each of the string names as a key, then the text in either markdown or HTML markup. I'd of course build the english one, and I'd look to others to translate. Would you be willing to be a translator?

**Comment by Eagle334** [comment]
Hello Aaron,
I can help for French translation, with pleasure. Bellow a screenshot with my current translation directly on the code. 
I agree with you about the priority on history. 
Currently the score is based on the number of donations for the current week (which is given by the API). But this value is only representative at the end of the week. So having at least the memory of the previous week would be better. For example, store the previous value when the news is smaller than the previous one (corresponds to the reset of the week).
![screencapture-teamfr](https://user-images.githubusercontent.com/37941899/52814372-43adb600-309c-11e9-811b-08077043ccbb.png)

**Comment by AaronTraas** [comment]
There's a little bugginess towards the beginning of the week that I'm trying to work out. But honestly, it's somewhat representative of most of the current week. We score not based on donations, but donations *per day*. 

I've not yet figured out exactly *when* the reset happens, or if it happens the same time for everyone, etc. This is something I have to fix.

My clan, honestly, isn't that interested in donations over time. We just use it as a metric of how active you've been lately. It would be useful to have 1-2 weeks back for us, but not more than that.

I'm open, though, to make the scoring more generic. If I wasn't interested in making this useful outside of my clan's needs, I wouldn't have allowed people to easily change the scoring values for various things.

Would you care to create a new ticket for this enhancement, detailing exactly how it would work?

**Comment by Eagle334** [comment]
Regarding your "We score not based on donations, but donations _per day_.".
The value calculated per day is the donation value of the current week divided by the number of days since the reset. 
As mentioned, this is not very relevant at the beginning of the week, because a player who doesn't connect much on Monday will give it a low score. It is only at the end of the week that the players can be compared.
My proposal is to save last week's value, and calculate the score by gradually switching to the new score. For example, the first day (1/7 of the week) Monday: (6*PreviousWeek + 1*CurrentWeek)/7. The last day (Sunday):  (1*PreviousWeek + 6*CurrentWeek)/7.
And display on the popup or on the cell the two value, the previous one and the current.
This allows you to manage exclusions on any day of the week with a good representation of player involvement.
What do you think ?
Donation is reset Sunday's at 8pm EST. The API does not provide this previous value (too bad).
I would have seen a code that compares the previous value (previous cron (hourly or less)) and the current value. If it is >, the new one replaces the previous one. If the new is <  than the previous one, it has been reset, and the value is saved to keep it for the whole week.

**Comment by AaronTraas** [comment]
Closing this one. If you want to recommend/refine any enhancements, please make one issue per enhancement, or comment on existing issues to clarify.
