### ISSUE TITLE
Proposal to improve the dashboard.

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#22]
<img width="851" alt="Capture d’écran 2019-05-08 à 22 29 22" src="https://user-images.githubusercontent.com/37941899/57406340-c8622900-71e0-11e9-8e70-553dc72a46c2.png">
I propose to take inspiration from site deckshop to indicate:

-  the number of places saved/lost (in addition to the current green or red arrow)
-  to have a different color depending on the grade.
-  to have the Last seen in hours (and not in days of inactivity)
-  indicate the number of cards given and received (and the average in popup)

**Comment by AaronTraas** [comment]
@Eagle334 what do you mean a different color depending on grade? What's the grade?

**Comment by AaronTraas** [comment]
Most of the relevant stuff was done in 2.7

**Comment by Eagle334** [comment]
Sorry for the delay on the question about grade and color.
On the example, we have a label with a color for Member, another for Elder, another for Co-Leader.
<img width="186" alt="Capture d’écran 2019-07-30 à 19 59 12" src="https://user-images.githubusercontent.com/37941899/62153313-95719200-b304-11e9-893c-8f8f244ff611.png">
