### ISSUE TITLE
Display at the bottom of the page the latest version available on Pypi.

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#23]
<img width="445" alt="Capture d’écran 2019-05-11 à 16 38 52" src="https://user-images.githubusercontent.com/37941899/57571296-67b73400-740c-11e9-8ff0-d0e91d283afe.png">
Actually the bottom of the page displays the current version used for the generation. 
It would be nice to display at the bottom of the page the latest version available on Pypi "(v.2.1.8 available, please update !)".

**Comment by AaronTraas** [comment]
Done in 2.1.9
