### ISSUE TITLE
Standings: Incorrect display especially when team names are long.

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#27]
Incorrect display especially when team names are long.
crtools 2.3.16
<img width="1259" alt="Capture d’écran 2019-06-19 à 22 25 41" src="https://user-images.githubusercontent.com/37941899/59797916-3bcb8000-92e1-11e9-8270-7d4e281c7513.png">

**Comment by LEO33SoFo** [comment]
I got this problem instead, since I updated to _2.3.16_.
![scr](https://user-images.githubusercontent.com/48962426/59811570-c2488780-930a-11e9-98b0-53f40d7a9448.png)

**Comment by AaronTraas** [comment]
@Eagle334 , @LEO33SoFo - I believe this is fixed in 2.4.4, can you please update and check?

**Comment by LEO33SoFo** [comment]
I confirm the issue has been fixed since the commit [12ced40](https://github.com/AaronTraas/Clash-Royale-Clan-Tools/commit/12ced40c0d32cc7cc422a36a3dac0a7964843d8a).
