### ISSUE TITLE
Enormous score calculation

### ISSUE THREAD

**Issue by LEO33SoFo** [AaronTraas/Clash-Royale-Clan-Tools#31]
I've got this problem: as soon as the clan's leader reached 6000 trophies, the total score reached over 30000 points! That score came from the war participation calculation. Is this a bug?
**crtools** is v.2.4.9.
![Screenshot](https://user-images.githubusercontent.com/48962426/60398134-2e21c000-9b55-11e9-9ad0-df57ec859eca.png)

**Comment by AaronTraas** [comment]
Yup -- that's a bug. Not an intended score bonus for people in that league :)

@LEO33SoFo -- what's your clan ID? I'd like to try and replicate this on my end and troubleshoot.

**Comment by AaronTraas** [comment]
Also, a link to your clan's web site.

**Comment by LEO33SoFo** [comment]
The clan's ID is _#2Q0809J_.
The clan's unofficial website is [https://leo33.info/maturerelaxed/](https://leo33.info/maturerelaxed/).

Notice that the trophy season has been reset now, so no players over 6000 trophies in my clan. You'll need to find a better clan to test this for now.
Also notice that no league icon was shown over the trophy number.

**Comment by AaronTraas** [comment]
No one in the entire league is over 5800 right now, it seems. I'll have to wait.

This may be a bug related to the new update. They may have rolled out changes to the API prior to the app. It's happened before; adding a new arena at one point caused a hard crash in my app.

I'll keep you posted.

**Comment by AaronTraas** [comment]
@LEO33SoFo - I think I tracked down the error and fixed it in version 2.4.11, but I couldn't perform a real-world test.

**Comment by AaronTraas** [comment]
OK, found a clan with a 6K dude. Fixed in 2.4.12
