### ISSUE TITLE
Some point about Translation

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#33]
1. The translation is not done on all the column for the same kind of sentence :
![2019-07-03 - 22 13 29](https://user-images.githubusercontent.com/37941899/60622965-d481f580-9de1-11e9-8673-a2bf4a697b18.gif)

2. Kick / Demote are not translated.
<img width="524" alt="Capture d’écran 2019-07-03 à 22 29 25" src="https://user-images.githubusercontent.com/37941899/60623045-08f5b180-9de2-11e9-8d29-fc6bc8eda22a.png">

3. "Days" is not translated ("jours" in French) 
<img width="505" alt="Capture d’écran 2019-07-03 à 22 30 38" src="https://user-images.githubusercontent.com/37941899/60623129-35113280-9de2-11e9-8ac3-0960cd984120.png">

**Comment by AaronTraas** [comment]
Thanks! This level of detail is super helpful for me to reproduce.

**Comment by AaronTraas** [comment]
Fixed in version 2.4.17
