### ISSUE TITLE
In Vacation : should be grayed independently  the score.

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#34]
When a player is set as 'in vacation', please disable the coloring of his score.
Example on my page. Eagle334 is in gray, but roni94 is red.... Gray for all the guy in vacation will be better.
<img width="1191" alt="Capture d’écran 2019-07-04 à 15 46 46" src="https://user-images.githubusercontent.com/37941899/60671247-fb3c3c80-9e72-11e9-8f6f-99202a83d353.png">

**Comment by AaronTraas** [comment]
Fixed in 2.7.5

**Comment by Eagle334** [comment]
Tested OK. Thanks.
