### ISSUE TITLE
Issue with a player name starting by "<"

### ISSUE THREAD

**Issue by Eagle334** [AaronTraas/Clash-Royale-Clan-Tools#36]
I have the player https://royaleapi.com/player/P0JQ28JC  = "<c2jojo"
In the web page, the name is empty :
<img width="960" alt="Capture d’écran 2019-08-08 à 22 17 31" src="https://user-images.githubusercontent.com/37941899/62735039-93a57e00-ba2a-11e9-9623-01f8aae9adf1.png">

**Comment by AaronTraas** [comment]
That's gross. I guess I need to filter user player through a HTML entities encoding function.

**Comment by AaronTraas** [comment]
Fixed in 2.7.8

**Comment by Eagle334** [comment]
Nice, now it's fine.
<img width="363" alt="Capture d’écran 2019-08-09 à 11 02 54" src="https://user-images.githubusercontent.com/37941899/62767577-4b6f7580-ba95-11e9-92d8-b4bc2141dcc6.png">
Thanks for this quick update. And i learn the expression "it's gross" :)
