### ISSUE TITLE
Locale can not be found

### ISSUE THREAD

**Issue by Rayman2200** [AaronTraas/Clash-Royale-Clan-Tools#40]
Hello,
I tried several versions via pip3 and get stuck with missing locales. Even when i select cn or fr as locale, the crtools can not find any locale.

```
crtools v2.10.0
Locale "en" not defined. Please use one of the following:
  - en : English (default)
  - fr : French
  - cn : Chinese
```

My enviroment is a docker container with python 3.7. (docker pull python:slim)

Any idea?

My Dockerfile looks llike

```
FROM python:slim
ADD .crtools /root
WORKDIR /root/
RUN mkdir /out && pip3 install crtools
CMD crtools --out /out 

```

**Comment by AaronTraas** [comment]
Can you please provide your crtools config file (with key removed, of course)?

What happens when you try to run it locally? I haven't tried it in a docker container. I do want to support this configuration, I just want to isolate variables.

Also, can you try running it with --debug?

**Comment by Rayman2200** [comment]
Hi Aaron,
I'm trying at the moment multiple machines, on my local pc it works. on my root server it doesn't also docker doesn't work.

on my local pc it starts working after different tries of building it from the repository and altering the python site after installing. doesn't know what exactly solve it. So I tried it with the docker container to get a clean enviroment with only python installed.

My config looks like

```
[API]
# API key provided for your account at https://developer.clashroyale.com
# Note that the key is limited to a specific list of public IP addresses
api_key=<myapikey>

# Your clan tag
clan_id=<myclantag>

# Proxy URL -- URL for proxy server, if needed
#proxy=https://my-proxy.com

# Proxy headers -- custom headers for proxy if needed
#proxy_headers=headers

[Paths]
# your output path. Where you want the static website to live.
out=/srv/http/cr

# Path to the logo artwork for clan. Must be PNG. Recommended at
# least 64x64 pixels.
clan_logo=~/myclan/logo.png

# Path to 
```the favicon file you want to use for this
favicon=~/myclan/favicon.ico

# Path to a file that contains arbitrary HTML for the site.
description_html=~/myclan/body.html

[www]
# Canonical URL for this site. Used for setting the rel=canonical
# link in the web site, as well as generating the robots.txt
# and sitemap.xml
canonical_url=https://localhost/

**Comment by AaronTraas** [comment]
I think I found what might be causing it. I was showing that error when I tried to grab the time/date formatting from the OS when it isn't found. I still have that check now, but show a different message, and continue. Now the check only happens if the locale isn't in the list.

Please try again with 2.10.1

**Comment by Rayman2200** [comment]
Thanks that works now.

**Comment by AaronTraas** [comment]
Great. Closing this.
