### ISSUE TITLE
ERROR:crtools.crtools:error: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Rayman2200** [AaronTraas/Clash-Royale-Clan-Tools#50]
**Describe the bug**
crtools stop working after a while without changing something.

**To Reproduce**
I think this steps can be used to reproduce the behavior:
ClanId: 8PQ0CCVP 
History: https://polska.clash-royal.tk/history.json

**Expected behavior**
crtools start working again

**Server (please complete the following information):**
 - OS: ArchLinux
 - Version latest
 - Python version 3.7.4

**Command line arguments**
crtools

**Console output**
With version 2.11.4:
```
crtools v2.11.4
*** update available: crtools v2.12.6 ***
Locale time setting not found in your os for "en"
- requesting info for clan id: #8PQ0CCVP
- clan: Polska (#8PQ0CCVP)
Traceback (most recent call last):
  File "/usr/bin/crtools", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/crtools/__init__.py", line 105, in main
    build_dashboard(config)
  File "/usr/lib/python3.7/site-packages/crtools/crtools.py", line 204, in build_dashboard
    members_processed = process_members(config, clan, warlog, current_war_processed, member_history)
  File "/usr/lib/python3.7/site-packages/crtools/crtools.py", line 129, in process_members
    members_processed.append(factory.get_processed_member(member_src))
  File "/usr/lib/python3.7/site-packages/crtools/memberfactory.py", line 23, in get_processed_member
    self.enrich_member_with_history(processed_member, self.member_history['members'][processed_member.tag])
  File "/usr/lib/python3.7/site-packages/crtools/memberfactory.py", line 39, in enrich_member_with_history
    last_seen = datetime.strptime(member.last_seen.split('.')[0], '%Y%m%dT%H%M%S')
AttributeError: 'NoneType' object has no attribute 'split'
```
With latest 2.12.6
```
crtools v2.12.6
Locale time setting not found in your os for "en"
- requesting info for clan id: #8PQ0CCVP
- clan: Polska (#8PQ0CCVP)
ERROR:crtools.crtools:error: 'NoneType' object has no attribute 'split'
```

**Comment by AaronTraas** [comment]
Have you tried running this again? I just ran it on my machine with your clan tag and your history.json, and it worked. Maybe a hiccup in the API and what it was returning? That's happened before on Supercell's end.

**Comment by Rayman2200** [comment]
I can confirm it. The crtools work again.

Just before this problem, one player rejoined us, after we kicked him days before. 

Thanks for your help.

**Comment by AaronTraas** [comment]
No problem. The reliability of the API is spotty at times. Sometimes they even change it in a way that breaks pyroyale, and I have to rush out an update.
