### ISSUE TITLE
member-table-sortable

### ISSUE THREAD

**Issue by spoofjack** [AaronTraas/Clash-Royale-Clan-Tools#51]
Wondering if there is a way to change the default sort for the HTML.
Right now the sort is defaulted by rank. I would like our members to see the point value first and foremost.
**Before:**
`                    <th class="rank" data-sort-default>#</th>
                    <th class="rank previous">Previous</th>
                    <th class="name">Member</th>
                    <th class="score">Score</th>
                    <th class="trophies">Trophies</th>
                    <th class="donations">Dona&shy;tions</th>
                    <th class="donations-received">Donations received</th>
                    <th class="inactivity">Days Inactive</th>
                    <th class="last-seen">Last Seen</th>
                    <th class="war-win-rate">War win rate</th>
                    <th class="war current" data-sort-method="none">Current War</th>`
**After:**
`                    <th class="score" data-sort-default>#</th>
                    <th class="name">Member</th>
                    <th class="rank">Score</th>
                    <th class="rank previous">Previous</th>
                    <th class="trophies">Trophies</th>
                    <th class="donations">Dona&shy;tions</th>
                    <th class="donations-received">Donations received</th>
                    <th class="inactivity">Days Inactive</th>
                    <th class="last-seen">Last Seen</th>
                    <th class="war-win-rate">War win rate</th>
                    <th class="war current" data-sort-method="none">Current War</th>`

**Comment by spoofjack** [comment]
I have this fixed to sort by "Score" in descending order so we can see our top scorers first and foremost. however i only hard coded the change.

https://github.com/spoofjack/Clash-Royale-Clan-Tools/commit/bcd069eac2db1efa0705aefc753d73ec0818b5b5

**Comment by AaronTraas** [comment]
I personally don't want that for my clan.

In order to make this something I'd accept, you need to make the default sorted column configurable. Every other clan that's used this has been happy having the clan sort by member # provided by the API.

**Comment by spoofjack** [comment]
I figured as much which is why i just closed the Issue. Member # was the same as trophies and i wanted to push my members to score more points

**Comment by AaronTraas** [comment]
The thing is, it is worth making this configurable.

Create a new property in config.py -- something like `config['member_table']['default-sort']` with the following possible values:

- `rank`
- `name`
- `score`
- `trophies`
- `donations`
- `donations-received`
- `inactivity`
- `last-seen`
- `war-win-rate`

And then inject `data-sort-default` attribute into the selected `<th>` based on that value
