### ISSUE TITLE
Battles Left Calculation

### ISSUE THREAD

**Issue by spoofjack** [AaronTraas/Clash-Royale-Clan-Tools#52]
I notice that the amount of battles left from crtools does not match clash Royale. Crtools is pulling total members in war and not the, from battles remaining. 
I'll take a look through the API to see if there's a call for this.
![Screenshot_20200122-200052_Clash Royale](https://user-images.githubusercontent.com/20948932/72948191-6c313c00-3d52-11ea-9c92-3a17e612ea2e.jpg)
![Screenshot_20200122-200039_Clash Royale](https://user-images.githubusercontent.com/20948932/72948205-78b59480-3d52-11ea-9a1c-5ad9e262f111.jpg)

**Comment by AaronTraas** [comment]
If you can figure out how to get that info, please let me know. I wasn't able to figure it out. All I could do is get the total number of players from each clan, and count the number of battles that were listed as completed.

**Comment by spoofjack** [comment]
If theres no API call would the clan with most battles @ start of war work?  = clan['participants']

 Everyone gets even battles correct?

**Comment by AaronTraas** [comment]
I'll take a look later today. I haven't looked at that part of the code in a while, to be honest.
