### ISSUE TITLE
I am sure you noticed the news on Clanwars 2

### ISSUE THREAD

**Issue by heyudude** [AaronTraas/Clash-Royale-Clan-Tools#57]
**Is your feature request related to a problem? Please describe.**
The new API and new Clanwars 2 in CR will have major impact on CRTools

**Describe the solution you'd like**
I was just wondering if you are considering adding the new features to CRTools?
We as clan(s) love the tool and wold like to keep sing it.

**Describe alternatives you've considered**
There is no alternative to the website generation of CRTools :)

**Comment by AaronTraas** [comment]
Yes, it will be updated, but not right away. I don't know how things will change in the API yet. As far as I know, they didn't share that with the world. Not even sure it will continue to work when the changes are made. At this point, we have to wait and see. 

Also, I need to come up with new scoring algorithms and such. Please join the user/developer discord if you want to be notified about updates.

**Comment by heyudude** [comment]
Thanks! Of course the details are not known yet but I can join and contribute where needed. Some basic knowledge is available. I wanted to see if we could us crtools as basis for bstools for Brawl Stars also. But that is a longer term conversion path.

**Comment by AaronTraas** [comment]
I don't play Brawl Stars, but if you want to fork this and use it to make a clan management tool for that, that would be cool. I also don't know if they released an API for it.

The way I approached this is a two-project approach. I created a library called `clashroyale-swagger` (https://github.com/AaronTraas/clashroyale-swagger), which I used the OpenAPI language to describe the API. I used that to generate the code for the `pyroyale` python library (https://github.com/AaronTraas/pyroyale). And that library I used to get the data for `crtools`. I'd personally suggest a similar approach. I could help you with this if you like.

**Comment by heyudude** [comment]
Thanks, I already started forking and creating the API definition for Brawl Stars. developer.brawlstars.com is live but rather limited in calls. Indeed I take the same route as you. Why invent the wheel twice? I have a look at the swagger project. I must tell you I am on a steep learning path on API's and Python. So slow but steadily I learn (and enjoy). Any help is appreciated.

**Comment by AaronTraas** [comment]
@heyudude Hop on to the developer discord - https://discord.gg/K2UDCXU and I'm happy to discuss stuff.
