### ISSUE TITLE
history: track wars beyond the last 10

### ISSUE THREAD

**Issue by AaronTraas** [AaronTraas/Clash-Royale-Clan-Tools#7]
Track the status of all wars in perpetuity.

Add configuration as to how much we're storing, and how many wars we display

**Comment by AaronTraas** [comment]
Full test coverage needed, also

**Comment by Eagle334** [comment]
I have a Google Sheet table where I keep the battles of the clan wars. And I do my statistics taking into account the last 6 weeks, so the last 3 seasons. 
A Member becomes Elder if he has respected the rules (donations, if participating in wars do all the fight) during 3 weeks. I am merciless :)

**Comment by AaronTraas** [comment]
> I have a Google Sheet table where I keep the battles of the clan wars. And I do my statistics taking into account the last 6 weeks, so the last 3 seasons.
> A Member becomes Elder if he has respected the rules (donations, if participating in wars do all the fight) during 3 weeks. I am merciless :)
> This history allows some other stats, as the average crown per season, the number of participants......
> But also to cross-reference the data and see if you earn more when you are fewer in number, or when you earn more cards on the first day, etc.

Customizing the recommendation engine will come much, much later. Will likely require the user to write a Python function to do so.
