### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by AaronTraas** [AaronTraas/Clash-Royale-Clan-Tools#8]
All strings displayed to user, other than debug messages, must be abstracted for i18n.

**Comment by AaronTraas** [comment]
@Eagle334, I'm about to finish the first pass at multilingual support. I'm going to send you a template for translation into French for you to fill out.

**Comment by Eagle334** [comment]
Yes, with pleasure. ;-)

**Comment by AaronTraas** [comment]
Please edit this file: https://github.com/AaronTraas/Clash-Royale-Clan-Tools/blob/i18n/crtools/locale/fr/LC_MESSAGES/crtools.po

**Comment by AaronTraas** [comment]
Complete in 2.1.0.
